{% set name = 'bob.bio.video' %}
{% set project_dir = environ.get('RECIPE_DIR') + '/..' %}

package:
  name: {{ name }}
  version: {{ environ.get('BOB_PACKAGE_VERSION', '0.0.1') }}

build:
  number: {{ environ.get('BOB_BUILD_NUMBER', 0) }}
  run_exports:
    - {{ pin_subpackage(name) }}
  script:
    - cd {{ project_dir }}
    {% if environ.get('BUILD_EGG') %}
    - python setup.py sdist --formats=zip
    {% endif %}
    - python setup.py install --single-version-externally-managed --record record.txt

requirements:
  host:
    - python {{ python }}
    - setuptools {{ setuptools }}
    - numpy {{ numpy }}
    - h5py {{ h5py }}
    - scikit-learn {{ scikit_learn }}
    - bob.extension
    - bob.io.base
    - bob.io.video
    - bob.bio.base
    - bob.bio.face
  run:
    - python
    - setuptools
    - {{ pin_compatible('numpy') }}
    - {{ pin_compatible('h5py') }}
    - {{ pin_compatible('scikit-learn') }}

test:
  imports:
    - {{ name }}
  commands:
    - nosetests --with-coverage --cover-package={{ name }} -sv {{ name }}
    - sphinx-build -aEW {{ project_dir }}/doc {{ project_dir }}/sphinx
    - sphinx-build -aEb doctest {{ project_dir }}/doc sphinx
    - conda inspect linkages -p $PREFIX {{ name }}  # [not win]
    - conda inspect objects -p $PREFIX {{ name }}  # [osx]
  requires:
    - nose {{ nose }}
    - pytest {{ pytest }}
    - coverage {{ coverage }}
    - sphinx {{ sphinx }}
    - sphinx_rtd_theme {{ sphinx_rtd_theme }}
    - dask {{ dask }}
    - bob.db.atnt
    - bob.io.image

about:
  home: https://www.idiap.ch/software/bob/
  license: BSD License
  summary: Run biometric recognition algorithms on videos
  license_family: BSD
